#! /bin/sh 

########################################################################
#
# File:   install.sh
# Author: Mark Mitchell
# Date:   08/10/98
#
# Contents:
#
# Copyright (c) 1997 by Mark Mitchell.  All rights reserved. 
#
########################################################################

# This file is a dummy, used to satisfy configure.
